<a href="https://colab.research.google.com/github/sanjaya999/Pytorch/blob/main/pytorchFundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import torch
print(torch.__version__)

2.5.1+cu124


##introduction to tensors
###creating a tensor

Pytorch tensors are created using torch.Tensor()


In [5]:
#scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.ndim #number of dimensions

In [6]:
scalar.item()

7

In [8]:
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [9]:
vector.shape

torch.Size([2])

In [12]:
##MATRIX
MATRIX = torch.tensor([[7,8],[5,2]])
MATRIX

tensor([[7, 8],
        [5, 2]])

In [13]:
MATRIX.ndim #2square braket

2

*MATRIX*[1]

In [16]:
MATRIX.shape

torch.Size([2, 2])

In [19]:
TENSOR.ndim

3

In [20]:
TENSOR.shape

torch.Size([1, 3, 3])

In [23]:
TENSOR[0]

tensor([[1, 1, 1],
        [3, 6, 9],
        [2, 5, 4]])