<a href="https://colab.research.google.com/github/sanjaya999/Pytorch/blob/main/pytorchFundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch
print(torch.__version__)

2.5.1+cu124


##introduction to tensors
###creating a tensor

Pytorch tensors are created using torch.Tensor()


In [3]:
#scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [4]:
scalar.ndim #number of dimensions

0

In [5]:
scalar.item()

7

In [6]:
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [7]:
vector.shape

torch.Size([2])

In [8]:
##MATRIX
MATRIX = torch.tensor([[7,8],[5,2]])
MATRIX

tensor([[7, 8],
        [5, 2]])

In [9]:
MATRIX.ndim #2square braket

2

*MATRIX*[1]

In [10]:
MATRIX.shape

torch.Size([2, 2])

###Random tensors Why random tensors?
Random tenstors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data
`start with random numbers -> look at data ->update random numbers -> look at data -> update random numbers`

In [11]:
# Create a random tensor of size (3,4)
random_tensor = torch.rand(5,4)
random_tensor

tensor([[0.7798, 0.1384, 0.8644, 0.6749],
        [0.2814, 0.7513, 0.8287, 0.9959],
        [0.9182, 0.4337, 0.7835, 0.3787],
        [0.3266, 0.8638, 0.1541, 0.4449],
        [0.1323, 0.8268, 0.3359, 0.3363]])

*italicized text*

In [12]:
#create a random tensor with similar shape to image tensor
random_image_size_tensor = torch.rand(size = (224 , 224 , 3)) #height , width , color channel RGB
random_image_size_tensor.shape , random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [13]:
torch.rand(size =(3,3))

tensor([[0.7514, 0.7272, 0.9673],
        [0.8336, 0.8604, 0.0557],
        [0.8599, 0.4490, 0.4531]])

In [14]:
### 0s and 1s
zero = torch.zeros(size = (3,4)) ### multiplying any tensor with zero is zerotensor
zero


tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [15]:
one = torch.ones(4,4)
one

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [16]:
one.dtype ###dataType they are float32

torch.float32

creating a range of tensors and tensors-like

In [17]:
zeroToTen = torch.arange(0 , 10  ) ### 0 to 10  after range you can also give step like 2

In [18]:
tenzeros = torch.zeros_like(input = zeroToTen)
tenzeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [19]:
###Tensor datatypes

In [20]:
##dataype eg float32/16 ,   device is if cpu / gpu cuda , grad is gradience
float_32 = torch.tensor([3.0,6.0,9.0] , dtype= None , device=None , requires_grad=False)
float_32.dtype

torch.float32

In [21]:
float16Tensor = float_32.type(torch.float16)
float16Tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [22]:
mul = float16Tensor * float_32
mul

tensor([ 9., 36., 81.])

###Tensor operation include :
addition , substraction , division , multiplication , matrix multiplication

In [23]:
tensor = torch.tensor([1,2,3])
tensor +10

tensor([11, 12, 13])

In [24]:
tensor * 10

tensor([10, 20, 30])

In [25]:
tensor / 5

tensor([0.2000, 0.4000, 0.6000])

In [26]:
tensor - 10

tensor([-9, -8, -7])

In [27]:
###inbuilt function
torch.mul(tensor , 10)
#torch.add ... etc


tensor([10, 20, 30])

###Matrix multiplication
mainly two way in neural network and deeplearning
1. element-wise multiplication
2. Matrix multiplication (dot product)

In [28]:
#element wise multiplication
tensor * tensor

tensor([1, 4, 9])

In [29]:
#Matrix multiplication
torch.matmul(tensor , tensor) # 1*1 + 2*2 + 3*3

tensor(14)

In [30]:
tensor1 = torch.rand(3,3)
tensor2 = torch.rand(3,3)
mul = torch.matmul(tensor1 , tensor2) # tensor1 @ tensor2 also does the same
mul

tensor([[0.2321, 0.9770, 0.7902],
        [0.0720, 0.1678, 0.1154],
        [0.1334, 0.8642, 0.6721]])

In [31]:
## finiding tensor aggregation min max sum etc

x = torch.arange(0,100)
torch.min(x) , torch.max(x)

## torch.mean(x.tmype(torch.float32))

In [39]:
x = torch.rand(5,5)

torch.sum(x) , x.sum()m

In [35]:
##finding positional min and max

In [40]:
x.argmin()  # position where there is minimum value => return index i

tensor(2)

In [41]:
x.argmax()# position where there is maximum valeu => return index  i

tensor(12)

##reshaping - reshaps an input tensor to defined shape
## view -  return a view of input tensor of shape but keep the same memory as the original tensor
#stack - combine multiple tensors on top of eachother vstack or side by side hstack
# squeez removes all 1 dimensions from tensor
' unsqueze add all dimension in target tensor'
#permute = reture a view of the input wiht dimesoion permuted swap in certain way

In [42]:
x = torch.arange(1. , 10.)
x , x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [46]:
#add extra dimension
x_reshape = x.reshape(3,3)
x_reshape , x.shape

(tensor([[1., 2., 3.],
         [4., 5., 6.],
         [7., 8., 9.]]),
 torch.Size([9]))